apiVersion: apps/v1
kind: Deployment
metadata:
  name: doitu-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doitu
  template:
    metadata:
      labels:
        app: doitu
    spec:
      containers:
      - name: doitu
        image: player7571/doitu:latest
        ports:
        - containerPort: 80
