version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: doitu-mysql-container2
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: doitu
      TZ: Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
